name = "sidan-lab/aiken-example"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'sidan-lab/aiken-example'"

[repository]
user = "sidan-lab"
project = "aiken-example"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
